### ISSUE TITLE
Investigate Concourse AWS AMI Tracking Resource

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/cg-deploy-concourse#207]
Review Concourse CI to establish if a AWS AMI tracking resource exists so Concourse can track updates to published AWS AMIs to trigger deploys in pipelines

## Notes

- The resource needs to support non-public/private AMI tracking outside on our AWS accounts

## Acceptance Criteria

- [ ] Document the location and usage of the resource

**Comment by spgreenberg** [comment]
No such resource according to: https://resource-types.concourse-ci.org/

**Comment by spgreenberg** [comment]
No such resource according to: https://resource-types.concourse-ci.org/
