### ISSUE TITLE
Deploy dedicated Production Concourse Deployment for Pages Usage

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/cg-deploy-concourse#221]
In the current tooling environment, deploy a new instance of Concourse for pages usage

## Notes

- Start with the following config: 2 web nodes and 2 worker nodes
- Opsuaa - mirror existing resources used by Concourse and pages for access
- BOSH - new tooling vm extension

## Acceptance Criteria

- [ ] New environment is defined

**Comment by soutenniza** [comment]
Done!
